spring:
  datasource:
    username: root
    password: 1q2w3e4r!!
    url: jdbc:mysql://smupool-mysql.ch6oyo2eaa5h.ap-northeast-2.rds.amazonaws.com:3306/smupool
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true # hibernate 로그